---
lb_hosts:
  hosts:
    wiezyczka-ollama-pc-01:
      ansible_host: 192.168.0.100
      ansible_port: 22
      ansible_user: ollama100
  vars:
    id_hosta: lb

k3s_hosts:
  children:
    serwer_inicjalizujacy:
      hosts:
        wiezyczka-ollama-pc-02:
          ansible_host: 192.168.0.101
          ansible_port: 22
          ansible_user: ollama101
      vars:
        id_hosta: serwer_init

    serwery:
      hosts:
        wiezyczka-ollama-pc-03:
          ansible_host: 192.168.0.102
          ansible_port: 22
          ansible_user: ollama102
        wiezyczka-ollama-pc-04:
          ansible_host: 192.168.0.103
          ansible_port: 22
          ansible_user: ollama103
      vars:
        id_hosta: serwer

    agenty:
      hosts:
        wiezyczka-ollama-pc-05:
          ansible_host: 192.168.0.104
          ansible_port: 22
          ansible_user: ollama104
      vars:
        id_hosta: agent