---
- name: "Aktualizacja systemu operacyjnego"
  become: true
  ansible.builtin.import_role:
    name: wspoldzielone
    tasks_from: aktualizacja_apt_so

- name: "Aktualizacja wszystkich pakietów"
  become: true
  ansible.builtin.import_role:
    name: wspoldzielone
    tasks_from: aktualizacja_apt_wszystkich_pakietow

- name: "Wyłączenie partycji wymiany"
  become: true
  ansible.builtin.import_role:
    name: wspoldzielone
    tasks_from: wylaczenie_partycji_wymiany

- name: "Konfiguracuja cgroups"
  become: true
  ansible.builtin.import_role:
    name: wspoldzielone
    tasks_from: konfiguracja_cgroups

- name: "Restart hosta"
  become: true
  ansible.builtin.import_role:
    name: wspoldzielone
    tasks_from: restart_hosta

- name: "Utworzenie ~/files"
  ansible.builtin.import_role:
    name: wspoldzielone
    tasks_from: utworzenie_katalogu_file_w_katalogu_domowym

- name: "Pobranie skryptu instalacyjnego k3s"
  ansible.builtin.import_role:
    name: wspoldzielone
    tasks_from: pobranie_k3s_install_sh

- name: "Instalacja głównego serwera k3s"
  ansible.builtin.command:
    cmd: "~/files/k3s-install.sh server --cluster-init --tls-san=192.168.0.101"
  environment:
    K3S_TOKEN: "SECRET"

- name: "Dwu minutowa przerwa, oczekiwanie na główny serwer k3s"
  pause:
    seconds: 120