---
- name: "Aktualizacja systemu operacyjnego"
  become: true
  ansible.builtin.import_role:
    name: wspoldzielone
    tasks_from: apt_aktualizacja_systemu_operacyjnego

- name: "Aktualizacja wszystkich pakietów"
  become: true
  ansible.builtin.import_role:
    name: wspoldzielone
    tasks_from: apt_aktualizacja_wszystkich_pakietow

- name: "Wyłączenie partycji wymiany"
  become: true
  ansible.builtin.import_role:
    name: wspoldzielone
    tasks_from: wylaczenie_partycji_wymiany

- name: "Konfiguracja cgroups"
  become: true
  ansible.builtin.import_role:
    name: wspoldzielone
    tasks_from: konfiguracja_cgroups

- name: "Restart komputera"
  become: true
  ansible.builtin.import_role:
    name: wspoldzielone
    tasks_from: restart_komputera

- name: "Utworzenie katalogu files w katalogu domowym"
  ansible.builtin.import_role:
    name: wspoldzielone
    tasks_from: utworzenie_katalogu_file_w_katalogu_domowym

- name: "Pobranie skryptu instalacyjnego k3s"
  ansible.builtin.import_role:
    name: wspoldzielone
    tasks_from: pobranie_k3s_install_sh

- name: "Zainstaluj k3s"
  include_tasks: "{{ rola_komputera }}.yml"