---
- name: "Uruchomienie lb_host"
  hosts: lb_hosts
  gather_facts: true
  serial:
    - 1
  roles:
    - lb_host

- name: "Uruchomienie serwera inicjalizujacego"
  hosts: serwer_inicjalizujacy
  gather_facts: true
  serial:
    - 1
  roles:
    - serwer_inicjalizujacy

- name: "Uruchomienie k3s_host"
  hosts: k3s_hosts:!serwer_inicjalizujacy
  gather_facts: true
  serial:
    - 1
    - 5
  max_fail_percentage: 25
  roles:
    - k3s_host