---
- name: "Przygotowanie środowiska wieżyczki ollama"
  hosts: all
  become: true
  gather_facts: true
  serial:
    - 1
    - 2
  max_fail_percentage: 25
  roles:
    - aktualizacja_systemu_operacyjnego
    - wylaczenie_partycji_wymiany
    - konfiguracja_cgroups