---
- name: "Pobranie obrazu nginx w wersji stabilnej"
  containers.podman.podman_image:
    name: docker.io/nginx:stable
- name: "Skopiowanie pliku konfiguracyjnego nginxa do hosta"
  copy:
    src: files/nginx.conf
    dest: "/files/nginx.conf"
- name: "Uruchomienie kontenera z nginxem"
  containers.podman.podman_container:
    name: lb
    image: docker.io/nginx:stable
    state: started
    detach: true
    restart_policy: always
    ports:
      - 6443:6443
    volumes: /files/nginx.conf:/etc/nginx/nginx.conf
- name: "Utworzenie katalogu ~/.config/systemd/user/ na hostach"
  ansible.builtin.file:
    path: ~/.config/systemd/user/
    state: directory
    mode: '0755'
- name: "Stworzenie serwisu systemd dla kontenera nginx"
  containers.podman.podman_generate_systemd:
    name: lb
    new: true
    no_header: true
    dest: "~/.config/systemd/user/"
- name: "Przeładuj systemd dla non-root user"
  ansible.builtin.systemd_service:
    daemon_reload: true
    scope: user
- name: "Uruchom lb.service"
  ansible.builtin.systemd_service:
    name: container-lb
    state: started
    enabled: true
    scope: user
- name: "Restart hosta"
  become: true
  ansible.builtin.import_role:
    name: restart_hosta